# Generated by Django 5.1.5 on 2025-01-17 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_rename_image_post_thumbnail_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='news_thumbnails', verbose_name='Nuotrauka'),
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news_images', verbose_name='Nuotrauka')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='web.post')),
            ],
            options={
                'verbose_name': 'Nuotrauka',
                'verbose_name_plural': 'Nuotraukos',
            },
        ),
    ]
