# Generated by Django 5.1.5 on 2025-01-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_post_thumbnail_postimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Darbuotojas')),
                ('division', models.CharField(max_length=100, verbose_name='Skyrius')),
                ('position', models.CharField(max_length=100, verbose_name='Pareigos')),
                ('phone', models.CharField(max_length=100, verbose_name='Telefonas')),
                ('email', models.EmailField(max_length=100, verbose_name='El. paštas')),
                ('show', models.BooleanField(default=True, verbose_name='Rodyti')),
            ],
            options={
                'verbose_name': 'Kontaktas',
                'verbose_name_plural': 'Kontaktai',
            },
        ),
    ]
