# Generated by Django 5.1.5 on 2025-01-23 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_employeecontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Pavadinimas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sukurta')),
            ],
            options={
                'verbose_name': 'biudžeto ataskaita',
                'verbose_name_plural': 'biudžeto ataskaitos',
            },
        ),
        migrations.CreateModel(
            name='BudgetReportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='budget_reports', verbose_name='Failas')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='web.budgetreport')),
            ],
            options={
                'verbose_name': 'Failas',
                'verbose_name_plural': 'Failai',
            },
        ),
    ]
