# Generated by Django 5.1.5 on 2025-01-28 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_financesreport_financesreportfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Pavadinimas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sukurta')),
            ],
            options={
                'verbose_name': 'Atlyginimų ataskaita',
                'verbose_name_plural': 'Atlyginimų ataskaitos',
            },
        ),
        migrations.CreateModel(
            name='SalaryReportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='salary_reports', verbose_name='Failas')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='web.salaryreport')),
            ],
            options={
                'verbose_name': 'Failas',
                'verbose_name_plural': 'Failai',
            },
        ),
    ]
