# Generated by Django 5.1.5 on 2025-02-05 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_salaryreport_salaryreportfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetQuarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Pavadinimas')),
            ],
            options={
                'verbose_name': 'Biudžeto ketvirtis',
                'verbose_name_plural': 'Biudžeto ketvirčiai',
            },
        ),
        migrations.RemoveField(
            model_name='budgetreportfile',
            name='report',
        ),
        migrations.AddField(
            model_name='budgetreportfile',
            name='quarter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='web.budgetquarter'),
        ),
    ]
