# Generated by Django 5.1.5 on 2025-02-05 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_budgetquarter_remove_budgetreportfile_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetquarter',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quarters', to='web.budgetreport'),
        ),
    ]
