# Generated by Django 5.1.5 on 2025-02-05 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_remove_financesreportfile_report_financesquarter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryQuarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Pavadinimas')),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quarters', to='web.salaryreport')),
            ],
            options={
                'verbose_name': 'Atlyginimų ketvirtis',
                'verbose_name_plural': 'Atlyginimų ketvirčiai',
            },
        ),
    ]
