# Generated by Django 5.1.5 on 2025-02-05 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_salaryquarter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaryreportfile',
            name='report',
        ),
        migrations.AddField(
            model_name='salaryreportfile',
            name='quarter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='web.salaryquarter'),
        ),
    ]
