# Generated by Django 5.1.5 on 2025-02-05 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_remove_salaryreportfile_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetquarter',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quarters', to='web.budgetreport', verbose_name='Ataskaita'),
        ),
        migrations.AlterField(
            model_name='budgetreportfile',
            name='quarter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='web.budgetquarter', verbose_name='Ketvirtis'),
        ),
        migrations.AlterField(
            model_name='financesquarter',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quarters', to='web.financesreport', verbose_name='Ataskaita'),
        ),
        migrations.AlterField(
            model_name='financesreportfile',
            name='quarter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='web.financesquarter', verbose_name='Ketvirtis'),
        ),
        migrations.AlterField(
            model_name='salaryquarter',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quarters', to='web.salaryreport', verbose_name='Ataskaita'),
        ),
        migrations.AlterField(
            model_name='salaryreportfile',
            name='quarter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='web.salaryquarter', verbose_name='Ketvirtis'),
        ),
    ]
