# Generated by Django 5.1.5 on 2025-03-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100, verbose_name='Markė')),
                ('model', models.CharField(max_length=100, verbose_name='Modelis')),
                ('year', models.CharField(max_length=100, verbose_name='Metai')),
                ('plate', models.CharField(max_length=100, verbose_name='Valstybinis numeris')),
                ('category', models.CharField(max_length=100, verbose_name='Kategorija')),
            ],
            options={
                'verbose_name': 'Automobilis',
                'verbose_name_plural': 'Automobiliai',
            },
        ),
    ]
