# Generated by Django 5.1.5 on 2025-03-16 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Pavadinimas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sukurta')),
            ],
            options={
                'verbose_name': 'Pirkimų ataskaita',
                'verbose_name_plural': 'Pirkimų ataskaitos',
            },
        ),
        migrations.CreateModel(
            name='TenderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tender_reports', verbose_name='Failas')),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='web.tenderreport', verbose_name='Ataskaita')),
            ],
            options={
                'verbose_name': 'Failas',
                'verbose_name_plural': 'Failai',
            },
        ),
    ]
