# Generated by Django 5.1.5 on 2025-06-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_tenderreport_tenderfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Pavadinimas')),
                ('file', models.FileField(upload_to='legal_documents', verbose_name='Failas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sukurta')),
            ],
            options={
                'verbose_name': 'Teisinis dokumentas',
                'verbose_name_plural': 'Teisiniai dokumentai',
            },
        ),
    ]
